### ISSUE TITLE
slow/undead server kills client

### ISSUE THREAD

**Issue by leitmedium** [bk-one/shoutbox-client#3]
When a shoutbox server is more or less dead (in this case alive but nearly not responding) the following breaks your code:

Timeout::Error
/usr/lib64/ruby/1.9.1/net/protocol.rb:140:in `rescue in rbuf_fill'
/usr/lib64/ruby/1.9.1/net/protocol.rb:134:in`rbuf_fill'
/usr/lib64/ruby/1.9.1/net/protocol.rb:116:in `readuntil'
/usr/lib64/ruby/1.9.1/net/protocol.rb:126:in`readline'
/usr/lib64/ruby/1.9.1/net/http.rb:2211:in `read_status_line'
/usr/lib64/ruby/1.9.1/net/http.rb:2200:in`read_new'
/usr/lib64/ruby/1.9.1/net/http.rb:1183:in `transport_request'
/usr/lib64/ruby/1.9.1/net/http.rb:1169:in`request'
/usr/lib64/ruby/gems/1.9.1/gems/shoutbox-client-0.1.1/lib/shoutbox_client.rb:39:in `block in update_status'
/usr/lib64/ruby/1.9.1/net/http.rb:627:in`start'
/usr/lib64/ruby/1.9.1/net/http.rb:490:in `start'
/usr/lib64/ruby/gems/1.9.1/gems/shoutbox-client-0.1.1/lib/shoutbox_client.rb:31:in`update_status'
/usr/lib64/ruby/gems/1.9.1/gems/shoutbox-client-0.1.1/lib/shoutbox_client.rb:21:in `shout'

**Comment by leitmedium** [comment]
Please note: This errror does not occur when the server isn't running at all. Gem version 0.1.1
